-- options.lua - Neovim options
-- Generated by homestruct

local opt = vim.opt

-- Line numbers
opt.number = true
opt.relativenumber = true

-- Indentation
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.autoindent = true

-- Search
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = true
opt.incsearch = true

-- Appearance
opt.termguicolors = true
opt.signcolumn = "yes"
opt.cursorline = true
opt.scrolloff = 8
opt.sidescrolloff = 8

-- Behavior
opt.wrap = false
opt.swapfile = false
opt.backup = false
opt.undofile = true
opt.undodir = vim.fn.stdpath("data") .. "/undo"

-- Split behavior
opt.splitright = true
opt.splitbelow = true

-- Completion
opt.completeopt = { "menu", "menuone", "noselect" }

-- Clipboard
opt.clipboard = "unnamedplus"

-- Update time
opt.updatetime = 250
opt.timeoutlen = 300

-- File encoding
opt.encoding = "utf-8"
opt.fileencoding = "utf-8"

-- Leader key (set before loading plugins)
vim.g.mapleader = " "
vim.g.maplocalleader = " "
